### ISSUE TITLE
Consider using a released version for getting hugo

### ISSUE THREAD

**Issue by curiouslychase** [moonytheloony/Blog-Web#1]
Hey there,

RE: our thread in the Hugo issues, I wanted to see if I could see how you were getting hugo.

Using `go get -u -v github.com/spf13/hugo` is going to get the latest version of hugo on master, which means it could be wildly different from the last time you built your site with the version of hugo you use.

I would recommend installing a stable tarball that you know is unchanged, like this:

https://gitlab.com/chaseadamsio/chaseadamsio.gitlab.io/blob/master/script/cibuild-pre#L1

By grabbing the tarball and using it instead, you guarantee that there will be no changes in the hugo implementation.

**Comment by rahulrai-in** [comment]
Fixed the deployment script. Thank you for your help.
