### ISSUE TITLE
"hugo --source=. --destination=export" encounter error

### ISSUE THREAD

**Issue by luckypoemster** [moonytheloony/Blog-Web#2]
hi.

root@localhost:/usr/local/hugo-site/examples/rahulrai.in# hugo --source=. --destination=export
Started building sites ...
ERROR 2017/04/16 06:38:26 Error while rendering "page": template: _default/single.html:3:3: executing "_default/single.html" at <partial "head.html" ...>: error calling partial: template: partials/head.html:16:86: executing "partials/head.html" at <.RSSlink>: can't evaluate field RSSlink in type *hugolib.PageOutput
root@localhost:/usr/local/hugo-site/examples/rahulrai.in#

how to fix it?

**Comment by rahulrai-in** [comment]
Please use the same version of Hugo as is there in the source. This code won't work with the latest release of hugo.

**Comment by luckypoem** [comment]
Which version is the code using?

**Comment by rahulrai-in** [comment]
0.17.

You can check the arguments at: https://github.com/moonytheloony/Blog-Web/blob/master/.travis.yml

Get Outlook for Android<https://aka.ms/ghei36>


________________________________
